name: build,test,upload sql server

on: 
  #workflow_dispatch
   workflow_call:
    secrets:
      Workflow2_PAT_TOKEN_GITHUB:
        required: true
      SONAR_TOKEN:
        required: true
      SONAR_HOST_URL:
        required: true
      token:
        required: true
    inputs:
      repoName:
        type: string
        required: true
        description: Application
      branchName:
        type: string
        required: true
        description: Branch Name    

env:
  TOKEN: ${{ secrets.SONAR_TOKEN }}
  URL: ${{ secrets.SONAR_HOST_URL }}
  REPOSITORY: ${{ inputs.repoName }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}



jobs:
  Build:
    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout from Repo
      uses: actions/checkout@v3
      with:
         repository: ${{ inputs.repoName }}
         ref: release/r-${{inputs.releaseNo}}
         token: ${{ secrets.GITHUB_TOKEN }}
      env:
         Workflow2_PAT_TOKEN_GITHUB: ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}
   
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        

    - name: Build database
      uses: credfeto/action-sql-format@v1.4.1
    
    - name: Run SonarQube Scan
      run: |
          echo "SONAR URL - > " ${{vars.SONAR_HOST_URL}}
          #export SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}
          export SONAR_HOST_URL=${{vars.SONAR_HOST_URL}}
          mvn install sonar:sonar \
            -D sonar.projectKey=test-maven-project \
            -D sonar.host.url=$SONAR_HOST_URL \
            -D sonar.login=admin -D sonar.password=admin123 
        
          
    - name: Build project with Maven
      run: mvn -B package --file pom.xml	 
        
    - name: Publish package
      run: mvn --batch-mode deploy
