name: dummy1

on:
  workflow_dispatch:
    #inputs:
     # manual_trigger:
      #  description: 'Manually trigger the workflow'
       # required: true
        #default: 'false'

#env:
 # JAVA_VERSION: '17'

jobs:
  dummy1:
    runs-on: self-hosted
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3
    
      - name: 'waiting'
        run : |
          sleep 5000s
  #dummy2:
   # runs-on: self-hosted
    #if: ${{ inputs.manual_trigger == 'true' }}
    #steps:
     # - name: 'Checkout GitHub Action'
        #uses: actions/checkout@v3
