name: Sleep Mode Workflow

on:
  workflow_dispatch:
    inputs:
      manual_trigger:
        description: 'Manually trigger the workflow'
        required: true
        default: 'false'

env:
  JAVA_VERSION: '17'

jobs:
  dummy1:

    runs-on: self-hosted

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

  dummy2:

    runs-on: self-hosted

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: Sleep for 5 minutes
        run: |
         echo "Sleeping for 5 minutes..."
         sleep 300  # 300 seconds = 5 minutes

      - name: Conditional Sleep
        run: |
         if [[ "${SLEEP_ENABLED}" == "true" ]]; then
           echo "Sleeping for 5 minutes..."
           sleep 300
         else
          echo "Sleep not enabled."
         fi
        env:
           SLEEP_ENABLED: ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}   
