name: reusable workflow

on:
  workflow_call:
   secrets:
      Workflow2_PAT_TOKEN_GITHUB:
        required: true
 
env:
  JAVA_VERSION: '17'                       

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3
      
    - name: Setup Java Sdk ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'

    - name: Run SonarQube Scan
      run: |
         echo "SONAR URL - > " ${{vars.SONAR_HOST_URL}}
         #export SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}
         export SONAR_HOST_URL=${{vars.SONAR_HOST_URL}}
         mvn install sonar:sonar \
           -D sonar.projectKey=test-maven-project \
           -D sonar.host.url=$SONAR_HOST_URL \
           -D sonar.login=admin -D sonar.password=admin123 
        
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml

    - name: Publish package
      run: mvn --batch-mode deploy      
