name: reusable workflow

on:
  workflow_call:
   secrets:
      Workflow2_PAT_TOKEN_GITHUB:
        required: true
      ANT_TOKEN:
        required: true
 
env:
  JAVA_VERSION: '17'
  MAVEN_SETTINGS_PATH: ${{ github.workspace }}/settings.xml
  Workflow2_PAT_TOKEN_GITHUB: ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}
  ANT_TOKEN: ${{ secrets.ANT_TOKEN }}
  

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3
      
    - name: Setup Java Sdk ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'adopt'

    - name: Run SonarQube Scan
      run: |
         echo "SONAR URL - > " ${{vars.SONAR_HOST_URL}}
         #export SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}
         export SONAR_HOST_URL=${{vars.SONAR_HOST_URL}}
         mvn install sonar:sonar \
           -D sonar.projectKey=test-maven-project \
           -D sonar.host.url=$SONAR_HOST_URL \
           -D sonar.login=admin -D sonar.password=admin123 
        
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml

    - name: Publish with Maven
      run: mvn clean deploy #--settings $MAVEN_SETTINGS_PATH
      env:
        ANT_TOKEN: ${{ secrets.ANT_TOKEN }}
        
   # - run: ant -noinput -buildfile build.xml
    #- uses: actions/upload-artifact@v3
     # with:
      # name: Package
       #path: build/jar 
    
   # - name: Download a single artifact
    #  uses: actions/download-artifact@v3
