name: reusable workflow

on:
  workflow_call:
   secrets:
      Workflow2_PAT_TOKEN_GITHUB:
        required: true
 
env:
  JAVA_VERSION: '17'                       

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3
      
    - name: Setup Java Sdk ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'

    - name: Run SonarQube Scan
      run: |
         echo "SONAR URL - > " ${{vars.SONAR_HOST_URL}}
         #export SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}
         export SONAR_HOST_URL=${{vars.SONAR_HOST_URL}}
         mvn install sonar:sonar \
           -D sonar.projectKey=test-maven-project \
           -D sonar.host.url=$SONAR_HOST_URL \
           -D sonar.login=admin -D sonar.password=admin123 
        
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
      
    - name: Publish to GitHub Packages
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}" >> ~/.npmrc
        echo "@lf-common-repo:registry=https://npm.pkg.github.com" >> ~/.npmrc
        jarFilePath=$(find . -name "*.jar" | head -n 1)  # Use the first JAR file found
        jarFileName=$(basename "$jarFilePath")
        echo "Publishing JAR: $jarFilePath"
        echo "Jar file name: $jarFileName"
        curl -XPUT -H "Authorization: Bearer ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}" \
            -H "Accept: application/vnd.github.v3+json" \
            --upload-file "$jarFilePath" \
            "https://npm.pkg.github.com/lf-common-repo/shared-workflow/$jarFileName"     

   # - run: ant -noinput -buildfile build.xml
    #- uses: actions/upload-artifact@v3
     # with:
      # name: Package
       #path: build/jar 
    
   # - name: Download a single artifact
    #  uses: actions/download-artifact@v3
