name: reusable workflow

on:
  workflow_call:
   secrets:
      Workflow2_PAT_TOKEN_GITHUB:
        required: true
 
env:
  JAVA_VERSION: '17'                       

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3
      
    - name: Setup Java Sdk ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
