name: React Native Build and Test

on:
 workflow_dispatch:

env:
  JAVA_VERSION: '17'
  NODE_VERSION: '14'
  
jobs:
  android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}  # Choose the appropriate Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build Android
        run: npm run android:build  # Replace with your actual Android build script

      - name: Set up Android emulator
        uses: wixplosives/actions-android-emulator@v2
        with:
          api-level: 30  # Adjust to your target API level
          package: 'system-images;android-30;google_apis;x86_64'
          script: |
            emulator -avd test -no-skin -no-audio -no-window &
            android-wait-for-emulator
            adb shell input keyevent 82 &

      - name: Run Android tests
        run: npm run android:test  # Replace with your actual Android test script

  ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}  # Choose the appropriate Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build iOS
        run: npm run ios:build  # Replace with your actual iOS build script

      - name: Set up Xcode
        uses: xcpretty/xcodebuild@v3

      - name: Run iOS emulator
        run: npm run ios:emulator  # Replace with your actual iOS emulator script

      - name: Run iOS tests
        run: npm run ios:test  # Replace with your actual iOS test script
